const plans = [
    {
      title: 'Welcome Package',
      features: [
        ['3 Buyer Connect Per Month', true],
        ['1 Complimentary Deal Per Year', false],
        ['Domain', true],
        ['Static Website', true],
        ['1 Business Email', true],
        ['Website Maintenance For 1 year', true],
        ['Responsive Website', true],
        ['SEO 1 Keyword (Local Searches)', true],
        ['Whatsapp Chat Integration', false],
        ['SSL', true],
        ['Favicon Icon', false],
        ['Live Chat Integration', false],
        ['Social Media Profile Creation & Posting', false],
        ['Company Certificate', false],
        ['Customer Support Person', true],
      ],
      price: '21999',
      highlighted: false,
    },
    {
      title: 'Premium Package',
      features: [
        ['5 Buyer Connect Per Month', true],
        ['1 Complimentary Deal Per Year', true],
        ['Domain', true],
        ['Static Website', true],
        ['2 Business Emails', true],
        ['Website Maintenance For 1 Year', true],
        ['Responsive Website', true],
        ['SEO 2 Keyword (Local Searches)', true],
        ['WhatsApp Chat Integration', true],
        ['SSL', true],
        ['Favicon Icon', false],
        ['Live Chat Integration', false],
        ['Social Media Profile Creation & Posting', false],
        ['Company Certificate', true],
        ['Customer Support Person', true],
      ],
      price: '41999',
      highlighted: true,
    },
    {
      title: 'Diamond Package',
      features: [
        ['7 Buyer Connect Per Month', true],
        ['3 Complimentary Deals Per Year', true],
        ['Domain', true],
        ['Dynamic Website', true],
        ['3 Business Emails', true],
        ['Website Maintenance For 1 Year', true],
        ['Responsive Website', true],
        ['SEO (4 to 5 Keywords)', true],
        ['WhatsApp Chat Integration', true],
        ['SSL', true],
        ['Favicon Icon', true],
        ['Live Chat Integration', true],
        ['Social Media Profile Creation & Posting', false],
        ['Company Certificate', true],
        ['Customer Support Person', true],
      ],
      price: '79999',
      highlighted: false,
    },
    {
      title: 'Premium Diamond',
      features: [
        ['15 Buyer Connect Per Month', true],
        ['4 Complimentary Deals Per Year', true],
        ['Domain', true],
        ['Dynamic Website', true],
        ['4 Business Emails', true],
        ['Website Maintenance For 1 Year', true],
        ['Responsive Website', true],
        ['SEO (6 to 8 Keywords)', true],
        ['WhatsApp Chat Integration', true],
        ['SSL', true],
        ['Favicon Icon', true],
        ['Live Chat Integration', true],
        ['Social Media Profile Creation & Posting', true],
        ['Company Certificate', true],
        ['Customer Support Person', true],
      ],
      price: '129999',
      highlighted: false,
    },
  ];
  
  export default plans;
  