const plans = [
  {
    title: 'Welcome Package',
    topService: [
      ['3 Conversations Buyer Connect Per Month', true],
      ['50 Leads enquiry Per Year', true],
      ['Company Certificate', true],
      ['Customer Support Person', true],
    ],
    website: [
      ['Single-page website (static)', true],
      ['Free domain & hosting (1 Year)', true],
      ['Mobile responsive design', true],
      ['Contact form integration', true],
      ['Free SSL integration (HTTPS security)', true],
      ['Basic SEO setup (title, meta tags)', true],
      ['1 round of revisions', true],
      ['Website Maintenance (3 Months)', true],
    ],
    seo: [
      ['Website audit & SEO report', true],
      ['3 keywords optimization (Local SEO)', true],
      ['On-page SEO (meta tags, alt tags, headings)', true],
      ['XML sitemap & robots.txt setup', true],
      ['Google Search Console setup', true],
      // ['1 blog post optimization per month', true],
      ['Monthly performance report', true],
    ],
    smo: [
      ['Setup & optimization of 2 social media accounts (FB, Insta)', true],
      ['Profile & cover design', true],
      ['5–7 posts per month (images + captions)', true],
      ['Hashtag research & usage', true],
      ['Quarterly performance report', true],
    ],
    price: '40000',
    highlighted: false,
  },
  {
    title: 'Premium Package',
    topService: [
      ['5 Conversations Buyer Connect Per Month', true],
      ['100 Leads enquiry Per Year', true],
      ['Company Certificate', true],
      ['Customer Support Person', true],
    ],
    website: [
      ['Up to 5 pages (Home, About, Services, Contact, Blog)', true],
      ['Free domain & hosting (1 Year)', true],
      ['CMS integration', true],
      ['SEO-friendly structure', true],
      ['Social media integration', true],
      ['Google Maps integration', true],
      ['Contact form', true],
      ['2 rounds of revisions', true],
      ['Basic speed optimization', true],
      ['Website Maintenance (6 Months)', true],
    ],
    seo: [
      ['10 keywords optimization', true],
      ['Technical SEO fixes (speed, mobile-friendliness)', true],
      ['Local SEO (Google Maps optimization)', true],
      ['Social Media linking', true],
      ['2 blog posts optimization per month', true],
      ['Competitor analysis', true],
      ['Monthly performance report + recommendations', true],
    ],
    smo: [
      ['Setup & optimization of 3–4 social media accounts (FB, Insta, LinkedIn, Twitter)', true],
['Monthly content: 10 posts and 5 reels (with captions and stories)', true],
      ['Audience engagement (likes, comments, replies)', true],
      ['Social media strategy for growth', true],
      ['Competitor analysis', true],
      ['Monthly insights report', true],
    ],
    price: '80000',
    highlighted: true,
  },
  {
    title: 'Diamond Package',
    topService: [
      ['8 Conversations Buyer Connect Per Month', true],
      ['2 Complimentary Deals Per Year', true],
      ['Company Certificate', true],
      ['Customer Support Person', true],
    ],
    website: [
      ['Custom UI/UX design & animations', true],
      ['Free domain & hosting (1 Year)', true],
      ['Unlimited pages', true],
      ['E-commerce functionality (Product categories, cart, checkout, payment gateway, product catalog, coupons & more)', true],
      ['Advanced SEO setup (on-page + local SEO)', true],
      ['Speed optimization (caching, CDN, compression)', true],
      ['Live Chat / Chatbot integration', true],
      ['Google Analytics & Search Console setup', true],
      ['Blog setup with categories & tags', true],
      ['Multi-language support', true],
      ['Website Maintenance (1 Year)', true],
    ],
    seo: [
      ['20+ keywords optimization', true],
      ['Advanced on-page & off-page SEO', true],
      ['Backlink building (high DA sites)', true],
      ['Content strategy & blog publishing (4 per month)', true],
      ['Schema markup integration (rich snippets)', true],
      ['Conversion tracking setup (Google Analytics, GTM)', true],
      ['Weekly keyword ranking report', true],
    ],
    smo: [
      ['Setup & management of 5+ platforms (FB, Insta, LinkedIn, Twitter, YouTube)', true],
      ['Monthly content: 20 posts and 5 reels (with captions and stories)', true],
      ['Ad campaign setup & management (FB/Insta ads)', true],
      ['Community management (group/page moderation)', true],
      ['Influencer collaboration strategy', true],
      ['Advanced analytics & growth tracking', true],
      ['Monthly insights report', true],
    ],
    price: '250000',
    highlighted: false,
  },
  {
    title: 'Premium Diamond',
    topService: [
      ['12 Conversations Buyer Connect Per Month', true],
      ['4 Complimentary Deals Per Year', true],
      ['Company Certificate', true],
      ['Customer Support Person', true],
    ],
    website: [
      ['Website + Mobile App integration (Android/iOS)', true],
      ['Free domain & hosting (1 Year)', true],
      ['Advanced security (firewall, malware protection)', true],
      ['Regular cloud backups & monitoring', true],
      ['Dedicated hosting & custom domain setup', true],
      ['Email marketing integration (newsletter system)', true],
      ['Digital marketing (SEO + SMO + Paid Ads setup)', true],
      ['Dedicated account manager', true],
      ['Play Store + App Store Publishing Support', true],
      ['Push Notifications + In-App Messaging + Email Notification', true],
      ['Payment Gateway + Wallet System + Subscriptions', true],
      ['Website Maintenance (1 Year)', true],
    ],
    seo: [
      ['30+ keywords optimization', true],
      ['Full technical SEO audit every month', true],
      ['Advanced backlink outreach (guest posts, PR links)', true],
      ['International SEO (multi-language / multi-location targeting)', true],
      ['Social media SEO optimization (FB, Insta, LinkedIn)', true],
      ['Paid ads strategy support (Google Ads, Meta Ads)', true],
      ['Dedicated SEO manager', true],
      ['24/7 support + monthly strategy meeting', true],
    ],
    smo: [
      ['Consistent daily posting (creative content)', true],
      ['7 reels and 2 YouTube videos (5–10 mins each) with professional editing', true],
      ['Paid ads campaigns across multiple platforms (FB, Insta, Twitter, YouTube', true],
      ['Social media contests & campaigns for engagement', true],
      ['Lead generation strategy through ads', true],
      ['Brand reputation management', true],
      ['Dedicated SMO manager', true],
      ['24/7 support + monthly strategy meeting', true],
    ],
    price: '800000',
    highlighted: false,
  },
];

export default plans;
