      .github/workflows/cicd.yml

      name: Deploy Next.js application

      on:
        push:
          branches:
            - deploy-with-docker-ec2

      jobs:
        build:
          runs-on: ubuntu-latest
          steps:
            - name: Checkout Source
              uses: actions/checkout@v4

            - name: Create .env file
              run: |
                echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> .env
                echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
                echo "TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }}" >> .env
                echo "TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}" >> .env
                echo "TWILIO_PHONE_NUMBER=${{ secrets.TWILIO_PHONE_NUMBER }}" >> .env
                echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
                echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
                echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
                echo "AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}" >> .env
